// -------------------------------------------------------------
// 
// File Name: hdlsrc\fft_st\dataMEM_re_0_2_16x16b.v
// Created: 2014-11-25 15:16:14
// 
// Generated by MATLAB 8.5 and HDL Coder 3.6
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dataMEM_re_0_2_16x16b
// Source Path: fft_st/fft_st/FFT HDL Optimized/RADIX2FFT_KernelF_2/dataMEM_re_0_2_16x16b
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dataMEM_re_0_2_16x16b
          (
           clk,
           enb,
           wr_din,
           wr_addr,
           wr_en,
           rd_addr,
           rd_dout
          );


  input   clk;
  input   enb;
  input   signed [15:0] wr_din;  // sfix16
  input   [3:0] wr_addr;  // ufix4
  input   wr_en;  // ufix1
  input   [3:0] rd_addr;  // ufix4
  output  signed [15:0] rd_dout;  // sfix16




  SimpleDualPortRAM_16x16b   u_SimpleDualPortRAM_16x16b   (.clk(clk),
                                                           .enb(enb),
                                                           .wr_din(wr_din),  // sfix16
                                                           .wr_addr(wr_addr),  // ufix4
                                                           .wr_en(wr_en),  // ufix1
                                                           .rd_addr(rd_addr),  // ufix4
                                                           .rd_dout(rd_dout)  // sfix16
                                                           );

endmodule  // dataMEM_re_0_2_16x16b

