vlib work
vlog  SimpleDualPortRAM_32x16b.v
vlog  dataMEM_re_0_1_32x16b.v
vlog  SimpleDualPortRAM_8x16b.v
vlog  dataXMEM_re_1_1_8x16b.v
vlog  Radix2ButterlyF.v
vlog  RADIX2FFT_KernelF_1.v
vlog  SimpleDualPortRAM_16x16b.v
vlog  dataMEM_re_0_2_16x16b.v
vlog  Radix2ButterlyF_block.v
vlog  RADIX2FFT_KernelF_2.v
vlog  ComplexMultiply.v
vlog  Radix2ButterlyF_block1.v
vlog  RADIX2FFT_KernelF_3.v
vlog  SimpleDualPortRAM_4x16b.v
vlog  dataMEM_re_4x16b.v
vlog  ComplexMultiply_block.v
vlog  Radix2ButterflyG.v
vlog  RADIX2FFT_KernelG.v
vlog  ComplexMultiply_block1.v
vlog  Radix2ButterflyG_block.v
vlog  RADIX2FFT_KernelG_block.v
vlog  ComplexMultiply_block2.v
vlog  Radix2ButterflyG_block1.v
vlog  RADIX2FFT_KernelL.v
vlog  SimpleDualPortRAM_64x16b.v
vlog  dataMEM_re_1_64x16b.v
vlog  RADIX2FFT_bitNatural.v
vlog  FFT_HDL_Optimized.v
vlog  SimpleDualPortRAM_128x32b.v
vlog  HDL_FIFO_ram_128x32b.v
vlog  HDL_FIFO.v
vlog  fft_st.v
