// -------------------------------------------------------------
// 
// File Name: hdlsrc\fft_st\Radix2ButterflyG_block1.v
// Created: 2014-11-25 15:16:15
// 
// Generated by MATLAB 8.5 and HDL Coder 3.6
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Radix2ButterflyG_block1
// Source Path: fft_st/fft_st/FFT HDL Optimized/RADIX2FFT_KernelL/Radix2ButterflyG
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Radix2ButterflyG_block1
          (
           clk,
           reset,
           enb,
           stageIn_6,
           procEnbReg,
           twdl_re_dly,
           twdl_im_dly,
           x_u_in,
           y_v_in,
           v_y_in,
           extended_dvld,
           softReset,
           stageOut_6,
           x_out,
           u_out,
           y_out,
           v_out,
           realOut_dvld,
           doutVld
          );


  input   clk;
  input   reset;
  input   enb;
  input   [2:0] stageIn_6;  // ufix3
  input   procEnbReg;
  input   signed [15:0] twdl_re_dly;  // sfix16_En14
  input   signed [15:0] twdl_im_dly;  // sfix16_En14
  input   signed [15:0] x_u_in;  // sfix16
  input   signed [15:0] y_v_in;  // sfix16
  input   signed [15:0] v_y_in;  // sfix16
  input   extended_dvld;
  input   softReset;
  output  [2:0] stageOut_6;  // ufix3
  output  signed [33:0] x_out;  // sfix34_En14
  output  signed [33:0] u_out;  // sfix34_En14
  output  signed [33:0] y_out;  // sfix34_En14
  output  signed [33:0] v_out;  // sfix34_En14
  output  realOut_dvld;
  output  doutVld;


  wire signed [31:0] multRes1;  // sfix32_En14
  wire signed [31:0] multRes2;  // sfix32_En14
  reg [2:0] Radix2ButterflyG_stageOut_reg;  // ufix3
  reg signed [15:0] Radix2ButterflyG_din1_pipe1;  // sfix16
  reg signed [15:0] Radix2ButterflyG_din1_pipe2;  // sfix16
  reg signed [15:0] Radix2ButterflyG_din1_pipe3;  // sfix16
  reg signed [32:0] Radix2ButterflyG_din1_pipe4;  // sfix33
  reg  Radix2ButterflyG_dinVld_pipe1;
  reg  Radix2ButterflyG_dinVld_pipe2;
  reg  Radix2ButterflyG_dinVld_pipe3;
  reg  Radix2ButterflyG_dinVld_pipe4;
  reg  Radix2ButterflyG_dinVld_pipe5;
  reg signed [33:0] Radix2ButterflyG_dout1_re_reg;  // sfix34
  reg signed [33:0] Radix2ButterflyG_dout1_im_reg;  // sfix34
  reg signed [33:0] Radix2ButterflyG_dout2_re_reg;  // sfix34
  reg signed [33:0] Radix2ButterflyG_dout2_im_reg;  // sfix34
  reg signed [32:0] Radix2ButterflyG_cmplxRes;  // sfix33
  reg  Radix2ButterflyG_realInVld_pipe1;
  reg  Radix2ButterflyG_realInVld_pipe2;
  reg  Radix2ButterflyG_realInVld_pipe3;
  reg  Radix2ButterflyG_realInVld_pipe4;
  reg  Radix2ButterflyG_realInVld_pipe5;
  reg [2:0] Radix2ButterflyG_stageOut_reg_next;  // ufix3
  reg signed [15:0] Radix2ButterflyG_din1_pipe1_next;  // sfix16
  reg signed [15:0] Radix2ButterflyG_din1_pipe2_next;  // sfix16
  reg signed [15:0] Radix2ButterflyG_din1_pipe3_next;  // sfix16
  reg signed [32:0] Radix2ButterflyG_din1_pipe4_next;  // sfix33_En14
  reg  Radix2ButterflyG_dinVld_pipe1_next;
  reg  Radix2ButterflyG_dinVld_pipe2_next;
  reg  Radix2ButterflyG_dinVld_pipe3_next;
  reg  Radix2ButterflyG_dinVld_pipe4_next;
  reg  Radix2ButterflyG_dinVld_pipe5_next;
  reg signed [33:0] Radix2ButterflyG_dout1_re_reg_next;  // sfix34_En14
  reg signed [33:0] Radix2ButterflyG_dout1_im_reg_next;  // sfix34_En14
  reg signed [33:0] Radix2ButterflyG_dout2_re_reg_next;  // sfix34_En14
  reg signed [33:0] Radix2ButterflyG_dout2_im_reg_next;  // sfix34_En14
  reg signed [32:0] Radix2ButterflyG_cmplxRes_next;  // sfix33_En14
  reg  Radix2ButterflyG_realInVld_pipe1_next;
  reg  Radix2ButterflyG_realInVld_pipe2_next;
  reg  Radix2ButterflyG_realInVld_pipe3_next;
  reg  Radix2ButterflyG_realInVld_pipe4_next;
  reg  Radix2ButterflyG_realInVld_pipe5_next;
  reg [2:0] stageOut_6_1;  // ufix3
  reg signed [33:0] x_out_1;  // sfix34_En14
  reg signed [33:0] u_out_1;  // sfix34_En14
  reg signed [33:0] y_out_1;  // sfix34_En14
  reg signed [33:0] v_out_1;  // sfix34_En14
  reg  realOut_dvld_1;
  reg  doutVld_1;
  reg signed [33:0] Radix2ButterflyG_add_cast;  // sfix34_En14
  reg signed [33:0] Radix2ButterflyG_add_cast_0;  // sfix34_En14
  reg signed [33:0] Radix2ButterflyG_add_cast_1;  // sfix34_En14
  reg signed [33:0] Radix2ButterflyG_add_cast_2;  // sfix34_En14
  reg signed [33:0] Radix2ButterflyG_sub_cast;  // sfix34_En14
  reg signed [33:0] Radix2ButterflyG_sub_cast_0;  // sfix34_En14
  reg signed [33:0] Radix2ButterflyG_sub_cast_1;  // sfix34_En14
  reg signed [33:0] Radix2ButterflyG_sub_cast_2;  // sfix34_En14
  reg signed [32:0] Radix2ButterflyG_add_cast_3;  // sfix33_En14
  reg signed [32:0] Radix2ButterflyG_add_cast_4;  // sfix33_En14
  reg signed [32:0] Radix2ButterflyG_sub_cast_3;  // sfix33_En14
  reg signed [32:0] Radix2ButterflyG_sub_cast_4;  // sfix33_En14


  ComplexMultiply_block2   u_complexMultiply   (.clk(clk),
                                                .enb(enb),
                                                .y_v_in(y_v_in),  // sfix16
                                                .v_y_in(v_y_in),  // sfix16
                                                .twdl_re_dly(twdl_re_dly),  // sfix16_En14
                                                .twdl_im_dly(twdl_im_dly),  // sfix16_En14
                                                .multRes1(multRes1),  // sfix32_En14
                                                .multRes2(multRes2)  // sfix32_En14
                                                );

  // Radix2ButterflyG
  always @(posedge clk)
    begin : Radix2ButterflyG_process
      if (reset == 1'b1) begin
        Radix2ButterflyG_din1_pipe1 <= 16'sb0000000000000000;
        Radix2ButterflyG_din1_pipe2 <= 16'sb0000000000000000;
        Radix2ButterflyG_din1_pipe3 <= 16'sb0000000000000000;
        Radix2ButterflyG_din1_pipe4 <= 33'sh000000000;
        Radix2ButterflyG_cmplxRes <= 33'sh000000000;
        Radix2ButterflyG_dinVld_pipe1 <= 1'b0;
        Radix2ButterflyG_dinVld_pipe2 <= 1'b0;
        Radix2ButterflyG_dinVld_pipe3 <= 1'b0;
        Radix2ButterflyG_dinVld_pipe4 <= 1'b0;
        Radix2ButterflyG_dinVld_pipe5 <= 1'b0;
        Radix2ButterflyG_realInVld_pipe1 <= 1'b0;
        Radix2ButterflyG_realInVld_pipe2 <= 1'b0;
        Radix2ButterflyG_realInVld_pipe3 <= 1'b0;
        Radix2ButterflyG_realInVld_pipe4 <= 1'b0;
        Radix2ButterflyG_realInVld_pipe5 <= 1'b0;
        Radix2ButterflyG_stageOut_reg <= 3'b000;
        Radix2ButterflyG_dout1_re_reg <= 34'sh000000000;
        Radix2ButterflyG_dout1_im_reg <= 34'sh000000000;
        Radix2ButterflyG_dout2_re_reg <= 34'sh000000000;
        Radix2ButterflyG_dout2_im_reg <= 34'sh000000000;
      end
      else begin
        if (enb) begin
          Radix2ButterflyG_stageOut_reg <= Radix2ButterflyG_stageOut_reg_next;
          Radix2ButterflyG_din1_pipe1 <= Radix2ButterflyG_din1_pipe1_next;
          Radix2ButterflyG_din1_pipe2 <= Radix2ButterflyG_din1_pipe2_next;
          Radix2ButterflyG_din1_pipe3 <= Radix2ButterflyG_din1_pipe3_next;
          Radix2ButterflyG_din1_pipe4 <= Radix2ButterflyG_din1_pipe4_next;
          Radix2ButterflyG_dinVld_pipe1 <= Radix2ButterflyG_dinVld_pipe1_next;
          Radix2ButterflyG_dinVld_pipe2 <= Radix2ButterflyG_dinVld_pipe2_next;
          Radix2ButterflyG_dinVld_pipe3 <= Radix2ButterflyG_dinVld_pipe3_next;
          Radix2ButterflyG_dinVld_pipe4 <= Radix2ButterflyG_dinVld_pipe4_next;
          Radix2ButterflyG_dinVld_pipe5 <= Radix2ButterflyG_dinVld_pipe5_next;
          Radix2ButterflyG_dout1_re_reg <= Radix2ButterflyG_dout1_re_reg_next;
          Radix2ButterflyG_dout1_im_reg <= Radix2ButterflyG_dout1_im_reg_next;
          Radix2ButterflyG_dout2_re_reg <= Radix2ButterflyG_dout2_re_reg_next;
          Radix2ButterflyG_dout2_im_reg <= Radix2ButterflyG_dout2_im_reg_next;
          Radix2ButterflyG_cmplxRes <= Radix2ButterflyG_cmplxRes_next;
          Radix2ButterflyG_realInVld_pipe1 <= Radix2ButterflyG_realInVld_pipe1_next;
          Radix2ButterflyG_realInVld_pipe2 <= Radix2ButterflyG_realInVld_pipe2_next;
          Radix2ButterflyG_realInVld_pipe3 <= Radix2ButterflyG_realInVld_pipe3_next;
          Radix2ButterflyG_realInVld_pipe4 <= Radix2ButterflyG_realInVld_pipe4_next;
          Radix2ButterflyG_realInVld_pipe5 <= Radix2ButterflyG_realInVld_pipe5_next;
        end
      end
    end

  always @(Radix2ButterflyG_stageOut_reg, Radix2ButterflyG_din1_pipe1,
       Radix2ButterflyG_din1_pipe2, Radix2ButterflyG_din1_pipe3,
       Radix2ButterflyG_din1_pipe4, Radix2ButterflyG_dinVld_pipe1,
       Radix2ButterflyG_dinVld_pipe2, Radix2ButterflyG_dinVld_pipe3,
       Radix2ButterflyG_dinVld_pipe4, Radix2ButterflyG_dinVld_pipe5,
       Radix2ButterflyG_dout1_re_reg, Radix2ButterflyG_dout1_im_reg,
       Radix2ButterflyG_dout2_re_reg, Radix2ButterflyG_dout2_im_reg,
       Radix2ButterflyG_cmplxRes, Radix2ButterflyG_realInVld_pipe1,
       Radix2ButterflyG_realInVld_pipe2, Radix2ButterflyG_realInVld_pipe3,
       Radix2ButterflyG_realInVld_pipe4, Radix2ButterflyG_realInVld_pipe5,
       stageIn_6, procEnbReg, x_u_in, multRes1, multRes2, extended_dvld) begin
    Radix2ButterflyG_dout1_re_reg_next = Radix2ButterflyG_dout1_re_reg;
    Radix2ButterflyG_dout1_im_reg_next = Radix2ButterflyG_dout1_im_reg;
    Radix2ButterflyG_dout2_re_reg_next = Radix2ButterflyG_dout2_re_reg;
    Radix2ButterflyG_dout2_im_reg_next = Radix2ButterflyG_dout2_im_reg;
    Radix2ButterflyG_cmplxRes_next = Radix2ButterflyG_cmplxRes;
    Radix2ButterflyG_stageOut_reg_next = stageIn_6 + 3'b001;
    if (Radix2ButterflyG_dinVld_pipe4) begin
      if (Radix2ButterflyG_realInVld_pipe4) begin
        Radix2ButterflyG_add_cast_1 = {Radix2ButterflyG_din1_pipe4[32], Radix2ButterflyG_din1_pipe4};
        Radix2ButterflyG_add_cast_2 = {Radix2ButterflyG_cmplxRes[32], Radix2ButterflyG_cmplxRes};
        Radix2ButterflyG_dout1_re_reg_next = Radix2ButterflyG_add_cast_1 + Radix2ButterflyG_add_cast_2;
        Radix2ButterflyG_sub_cast_1 = {Radix2ButterflyG_din1_pipe4[32], Radix2ButterflyG_din1_pipe4};
        Radix2ButterflyG_sub_cast_2 = {Radix2ButterflyG_cmplxRes[32], Radix2ButterflyG_cmplxRes};
        Radix2ButterflyG_dout2_re_reg_next = Radix2ButterflyG_sub_cast_1 - Radix2ButterflyG_sub_cast_2;
      end
      else begin
        Radix2ButterflyG_add_cast = {Radix2ButterflyG_din1_pipe4[32], Radix2ButterflyG_din1_pipe4};
        Radix2ButterflyG_add_cast_0 = {Radix2ButterflyG_cmplxRes[32], Radix2ButterflyG_cmplxRes};
        Radix2ButterflyG_dout1_im_reg_next = Radix2ButterflyG_add_cast + Radix2ButterflyG_add_cast_0;
        Radix2ButterflyG_sub_cast = {Radix2ButterflyG_din1_pipe4[32], Radix2ButterflyG_din1_pipe4};
        Radix2ButterflyG_sub_cast_0 = {Radix2ButterflyG_cmplxRes[32], Radix2ButterflyG_cmplxRes};
        Radix2ButterflyG_dout2_im_reg_next = Radix2ButterflyG_sub_cast - Radix2ButterflyG_sub_cast_0;
      end
    end
    Radix2ButterflyG_din1_pipe4_next = {{3{Radix2ButterflyG_din1_pipe3[15]}}, {Radix2ButterflyG_din1_pipe3, 14'b00000000000000}};
    Radix2ButterflyG_din1_pipe3_next = Radix2ButterflyG_din1_pipe2;
    Radix2ButterflyG_din1_pipe2_next = Radix2ButterflyG_din1_pipe1;
    Radix2ButterflyG_din1_pipe1_next = x_u_in;
    Radix2ButterflyG_dinVld_pipe5_next = Radix2ButterflyG_dinVld_pipe4;
    Radix2ButterflyG_dinVld_pipe4_next = Radix2ButterflyG_dinVld_pipe3;
    Radix2ButterflyG_dinVld_pipe3_next = Radix2ButterflyG_dinVld_pipe2;
    Radix2ButterflyG_dinVld_pipe2_next = Radix2ButterflyG_dinVld_pipe1;
    Radix2ButterflyG_dinVld_pipe1_next = extended_dvld;
    if (Radix2ButterflyG_realInVld_pipe3) begin
      Radix2ButterflyG_sub_cast_3 = {multRes1[31], multRes1};
      Radix2ButterflyG_sub_cast_4 = {multRes2[31], multRes2};
      Radix2ButterflyG_cmplxRes_next = Radix2ButterflyG_sub_cast_3 - Radix2ButterflyG_sub_cast_4;
    end
    else begin
      Radix2ButterflyG_add_cast_3 = {multRes1[31], multRes1};
      Radix2ButterflyG_add_cast_4 = {multRes2[31], multRes2};
      Radix2ButterflyG_cmplxRes_next = Radix2ButterflyG_add_cast_3 + Radix2ButterflyG_add_cast_4;
    end
    Radix2ButterflyG_realInVld_pipe5_next = Radix2ButterflyG_realInVld_pipe4;
    Radix2ButterflyG_realInVld_pipe4_next = Radix2ButterflyG_realInVld_pipe3;
    Radix2ButterflyG_realInVld_pipe3_next = Radix2ButterflyG_realInVld_pipe2;
    Radix2ButterflyG_realInVld_pipe2_next = Radix2ButterflyG_realInVld_pipe1;
    Radix2ButterflyG_realInVld_pipe1_next = procEnbReg;
    stageOut_6_1 = Radix2ButterflyG_stageOut_reg;
    x_out_1 = Radix2ButterflyG_dout1_re_reg;
    u_out_1 = Radix2ButterflyG_dout1_im_reg;
    y_out_1 = Radix2ButterflyG_dout2_re_reg;
    v_out_1 = Radix2ButterflyG_dout2_im_reg;
    realOut_dvld_1 = Radix2ButterflyG_realInVld_pipe5;
    doutVld_1 = Radix2ButterflyG_dinVld_pipe5;
  end



  assign stageOut_6 = stageOut_6_1;

  assign x_out = x_out_1;

  assign u_out = u_out_1;

  assign y_out = y_out_1;

  assign v_out = v_out_1;

  assign realOut_dvld = realOut_dvld_1;

  assign doutVld = doutVld_1;

endmodule  // Radix2ButterflyG_block1

