// -------------------------------------------------------------
// 
// File Name: hdlsrc\fft_st\SimpleDualPortRAM_8x16b.v
// Created: 2014-11-25 15:16:14
// 
// Generated by MATLAB 8.5 and HDL Coder 3.6
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SimpleDualPortRAM_8x16b
// Source Path: fft_st/fft_st/FFT HDL Optimized/RADIX2FFT_KernelF_1/dataXMEM_re_1_1_8x16b/SimpleDualPortRAM_8x16b
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SimpleDualPortRAM_8x16b
          (
           clk,
           enb,
           wr_din,
           wr_addr,
           wr_en,
           rd_addr,
           rd_dout
          );


  input   clk;
  input   enb;
  input   signed [15:0] wr_din;  // sfix16
  input   [2:0] wr_addr;  // ufix3
  input   wr_en;  // ufix1
  input   [2:0] rd_addr;  // ufix3
  output  signed [15:0] rd_dout;  // sfix16

  parameter addr_width = 2'd3;
  parameter data_width = 5'd16;

  reg  [data_width - 1:0] ram [2**addr_width - 1:0];
  reg  [data_width - 1:0] data_int;
  integer i;

  initial begin
    for (i=0; i<=2**addr_width - 1; i=i+1) begin
      ram[i] = 0;
    end
    data_int = 0;
  end


  always @(posedge clk)
    begin : SimpleDualPortRAM_8x16b_process
      if (enb == 1'b1) begin
        if (wr_en == 1'b1) begin
          ram[wr_addr] <= wr_din;
        end
        data_int <= ram[rd_addr];
      end
    end

  assign rd_dout = data_int;

endmodule  // SimpleDualPortRAM_8x16b

